files:
  - ".gitignore" # include
  - ".github"
  - ".vscode"
  - ".pre-commit-config.yml"
  - "LICENSE"
  - "README.md"

  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
  - "!.codespellignore"
  - "!src"
  - "!book.toml"
