repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        name: Check YAML syntax
        description: Validates YAML files like book.toml
        files: \.(toml|yaml|yml)$
      - id: check-toml
        name: Check TOML syntax
        description: Ensures book.toml is valid
        files: book\.toml$
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: Removes trailing whitespace in text files
        files: \.(md|toml)$
      - id: end-of-file-fixer
        name: Ensure newline at end of file
        description: Adds newline to end of Typst and other text files
        files: \.(md|toml)$
      - id: check-added-large-files
        name: Prevent large file commits
        description: Blocks large files like PDFs or fonts
        args: [--maxkb=500]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: Check spelling in text files
        description: Checks for common spelling mistakes in Typst, Markdown, and TOML        
        args: ["--ignore-words=.codespellignore"]
        files: ^.*\.(md|toml)$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # Use the latest stable version
    hooks:
      - id: detect-secrets
        name: Detect secrets within the codebase
        description: Detect and block secrets from committing to the codebase