repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        name: Check YAML syntax
        description: Validates YAML files like book.toml
        files: \.(toml|yaml|yml)$
      - id: check-toml
        name: Check TOML syntax
        description: Ensures book.toml is valid
        files: book\.toml$
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: Removes trailing whitespace in Typst and other text files
        files: \.(typ|md|toml)$
      - id: end-of-file-fixer
        name: Ensure newline at end of file
        description: Adds newline to end of Typst and other text files
        files: \.(typ|md|toml)$
      - id: check-added-large-files
        name: Prevent large file commits
        description: Blocks large files like PDFs or fonts
        args: [--maxkb=500]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: Check spelling in text files
        description: Checks for common spelling mistakes in Typst, Markdown, and TOML        
        args: ["--ignore-words=.codespellignore"]
        files: ^.*\.(typ|md|toml)$

  - repo: local
    hooks:
    - id: typstyle
      name: Format Typst files with typstyle
      description: Runs typstyle to standardize Typst file formatting
      entry: typstyle
      language: system
      files: \.typ$
      args: [--inplace, --verbose]